<a href="https://colab.research.google.com/github/MJaiman/ML/blob/main/linearregression_Multiple_variable_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!git clone https://github.com/MJaiman/ML

Cloning into 'ML'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 24 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (24/24), done.


In [5]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [6]:
df=pd.read_csv('/content/ML/Archive/homeprices.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
import math
medians_bedroom= math.floor(df.bedrooms.median())
medians_bedroom

4

In [8]:
df.bedrooms=df.bedrooms.fillna(medians_bedroom)
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
rc=reg.coef_
rc

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
ri=reg.intercept_
ri

221323.00186540396

In [12]:
reg.predict([[3000 , 3 , 40]])

array([498408.25158031])

In [13]:
ans=112.06244194*3000 + 23388.88007794*3 + (-3231.71790863)*40+221323.00186540396
ans

498408.251574024

In [14]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [15]:
import pickle

In [16]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [17]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [18]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
reg.predict([[3000 , 3 , 40]])

array([498408.25158031])

In [20]:
from sklearn.externals import joblib

In [21]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [22]:

mj=joblib.load('model_joblib')

In [23]:
mj.predict([[3000 , 3 , 40]])


array([498408.25158031])

In [24]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [25]:
mj.intercept_

221323.00186540396