<a href="https://colab.research.google.com/github/MJaiman/ML/blob/main/linear_regression_multiple_variable_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise**

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [23]:
!install.packages("readr")

/bin/bash: -c: line 0: syntax error near unexpected token `"readr"'
/bin/bash: -c: line 0: `install.packages("readr")'


In [24]:
!pip install word2number

In [25]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [26]:
df=pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')

In [27]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [28]:
df.experience=df.experience.fillna('zero')

In [29]:
df.experience=df.experience.apply(w2n.word_to_num)

In [30]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [31]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [34]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [35]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [37]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [39]:
reg.intercept_

14992.65144669314

In [40]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [41]:
ans = 2922.26901502*2 + 2221.30909959*9 + 2147.48256637*6 + 14992.65144669314
ans

53713.86677126314

In [42]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [43]:
ans = 2922.26901502*12 + 2221.30909959*10 + 2147.48256637*10 + 14992.65144669314
ans

93747.79628653315